block & block option
gsainfoteam/ams-be-2023 pull request #7
Opened 2023-09-18 10:35 UTC by controlZ

- create block api
- create block option api
- get block with block option api

2023-09-18 10:42 UTC, 2paperstar commented
fyi

#5 머지 된 이후 병합 리졸브하고 진행

2023-09-18 10:53 UTC, 2paperstar requested changes
good

2023-09-18 10:53 UTC, 2paperstar commented on src/block/entity/block.entity.ts
> +  deleted_at: Date;
@DeleteDateColumn

2023-09-18 10:53 UTC, 2paperstar commented on src/block/entity/block.entity.ts
> +  updated_at: Date;
@UpdateDateColumn

2023-09-18 10:53 UTC, 2paperstar commented on src/block/entity/block.entity.ts
> +  block_type: string;
enum 만들어주세요

2023-09-18 10:53 UTC, 2paperstar commented on src/block/dto/block.dto.ts
> +  block_type: string;
@IsEnum

2023-09-18 10:53 UTC, 2paperstar commented on src/block-option/dto/block-option.dto.ts
> +  option: string[];
options..

2023-09-18 10:53 UTC, 2paperstar commented on src/block-option/dto/block-option.dto.ts
> +  min: number;
default 1

2023-09-18 10:53 UTC, 2paperstar commented on src/block-option/dto/block-option.dto.ts
> +  max: number;
default 1

2023-09-18 10:53 UTC, 2paperstar commented on src/block/dto/block.dto.ts
> +}
mandatory: boolean;

2023-09-18 10:53 UTC, 2paperstar commented on src/block/block.service.ts
> +  }
여기 메소드 이름들은 repository 단에서 말하는 개념적인 동사가 들어있는 이름이에요

서비스 단에서 부를 수 있는 이름으로 바꿔주세요

2023-09-18 10:53 UTC, 2paperstar commented on src/block-option/block-option.controller.ts
> +    return { message: 'created successfully' };
만들어진걸 돌려줘요...

2023-09-18 10:53 UTC, 2paperstar commented on src/block/block.controller.ts
> +    return { message: 'created successfully' };
만들어진걸 돌려줘요...

2023-09-25 05:22 UTC, controlZ commented on src/block/dto/block.dto.ts
> +}
mandatory에도 default 걸어둘까용?

2023-09-25 05:23 UTC, 2paperstar commented on src/block/dto/block.dto.ts
> +}
좋습니다

2023-09-25 05:24 UTC, controlZ commented on src/block/dto/block.dto.ts
> +}
근데 default : true ?

2023-09-25 05:25 UTC, controlZ commented on src/block/dto/block.dto.ts
> +}
false ?

2023-09-25 05:26 UTC, 2paperstar commented on src/block/dto/block.dto.ts
> +}
구글 폼 기본값 따라가죠

2023-09-25 05:27 UTC, controlZ commented on src/block/dto/block.dto.ts
> +}
구글폼은 default : false네요 일단 이걸로 갈게여

2023-09-25 10:19 UTC, 2paperstar reviewed
일단 여기까진 OK 입니당 업데이트하는 것도 고려해주세요!

2023-10-04 09:35 UTC, 2paperstar requested changes
얘만 고치면 될듯

2023-10-04 09:35 UTC, 2paperstar commented on src/block/block.repository.ts
> +  ): Promise<Block | null> {
응답값 null 없게 (대신에 NotFoundException)

2024-01-03 09:52 UTC, merged